Repository kubernetes-sigs/wg-policy-prototypes, pull requests merged in 2020-09, with the labels that each got.

#14 repo url change in api doc generate
  policy-report/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9 Feature/7 selectors
  policy-report/api/v1alpha1/clusterpolicyreport_types.go
  policy-report/api/v1alpha1/policyreport_types.go
  policy-report/crd/policy.kubernetes.io_clusterpolicyreports.yaml
  policy-report/crd/policy.kubernetes.io_policyreports.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#17 selector added for scope and resources in policyreport
  policy-report/api/v1alpha1/clusterpolicyreport_types.go
  policy-report/api/v1alpha1/policyreport_types.go
  policy-report/crd/policy.kubernetes.io_clusterpolicyreports.yaml
  policy-report/crd/policy.kubernetes.io_policyreports.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#18 Proposal for grouping resource list by resource group and kind for a policy and a rule
  policy-report/api/v1alpha1/policyreport_types.go
  policy-report/crd/policy.kubernetes.io_clusterpolicyreports.yaml
  policy-report/crd/policy.kubernetes.io_policyreports.yaml
  policy-report/docs/index.html
  policy-report/go.mod
  policy-report/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL
