Repository kubernetes-sigs/wg-policy-prototypes, pull requests merged in 2021-03, with the labels that each got.

#39 oscal alignment
  policy-report/api/v1alpha1/policyreport_types.go
  policy-report/api/v1alpha1/zz_generated.deepcopy.go
  policy-report/crd/wgpolicyk8s.io_clusterpolicyreports.yaml
  policy-report/crd/wgpolicyk8s.io_policyreports.yaml
  policy-report/docs/index.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#41 update api-docs
  policy-report/docs/index.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#42 updates sample yaml files with right apiVersion and updates CRDs to v1 from v1 beta
  policy-report/Makefile
  policy-report/api/v1alpha1/policyreport_types.go
  policy-report/api/v1alpha1/zz_generated.deepcopy.go
  policy-report/crd/wgpolicyk8s.io_clusterpolicyreports.yaml
  policy-report/crd/wgpolicyk8s.io_policyreports.yaml
  policy-report/samples/sample-cis-k8s.yaml
  policy-report/samples/sample-co.yaml
  policy-report/samples/sample-rhacm-policy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#45 fix: fixes Timestamp JSON issue #44 and regenerates CRDs and docs
  policy-report/api/v1alpha1/policyreport_types.go
  policy-report/crd/wgpolicyk8s.io_clusterpolicyreports.yaml
  policy-report/crd/wgpolicyk8s.io_policyreports.yaml
  policy-report/docs/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M
