Repository kubernetes-sigs/wg-policy-prototypes, pull requests merged in 2021-04, with the labels that each got.

#47 release v1Aplha2 version of CRD
  policy-report/Makefile
  policy-report/api/v1alpha2/clusterpolicyreport_types.go
  policy-report/api/v1alpha2/doc.go
  policy-report/api/v1alpha2/groupversion_info.go
  policy-report/api/v1alpha2/policyreport_types.go
  policy-report/api/v1alpha2/zz_generated.deepcopy.go
  policy-report/crd/wgpolicyk8s.io_clusterpolicyreports.yaml
  policy-report/crd/wgpolicyk8s.io_policyreports.yaml
  policy-report/docs/index.html
Labels: approved, cncf-cla: yes, size/M

#48 updates samples to v1Alpha2
  policy-report/samples/sample-cis-k8s.yaml
  policy-report/samples/sample-co.yaml
  policy-report/samples/sample-rhacm-policy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#52 add source field
  go.mod
  go.sum
  policy-report/api/v1alpha2/policyreport_types.go
  policy-report/crd/wgpolicyk8s.io_clusterpolicyreports.yaml
  policy-report/crd/wgpolicyk8s.io_policyreports.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#53 regenerate HTML & files
  policy-report/docs/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#56 Add v1alpha1 types and schema
  policy-report/api/v1alpha1/clusterpolicyreport_types.go
  policy-report/api/v1alpha1/doc.go
  policy-report/api/v1alpha1/groupversion_info.go
  policy-report/api/v1alpha1/policyreport_types.go
  policy-report/api/v1alpha1/zz_generated.deepcopy.go
  policy-report/crd/v1alpha1/wgpolicyk8s.io_clusterpolicyreports.yaml
  policy-report/crd/v1alpha1/wgpolicyk8s.io_policyreports.yaml
  policy-report/crd/v1alpha2/wgpolicyk8s.io_clusterpolicyreports.yaml
  policy-report/crd/v1alpha2/wgpolicyk8s.io_policyreports.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL
